# -*- coding: utf-8 -*-
"""ttstest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJd7AtPJDM_N3fQqxqY_H3s1U5ZoFe_k
"""

!pip install git+https://github.com/dunjadakovic/Bark2

from bark import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio

#alle modelle herunterladen
preload_models()

#bitte hier prompt und speaker eingeben
text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs]
     But I also have other interests such as playing tic tac toe.
"""
history_prompt = "v2/sprache_speaker_nummer"#falls gewünscht, hier sprache und nummer des speakers eingeben, bsp: v2/en_speaker_1
audio_array = generate_audio(text_prompt, history_prompt)#falls history prompt unerwünscht, löschen

# audio speichern
write_wav("bark_generation.wav", SAMPLE_RATE, audio_array)

# audio ausgeben
Audio(audio_array, rate=SAMPLE_RATE)